version: '3'

services:
    web:
        build: .
        command: python -u flask_brevets.py
        volumes:
            - .:/app/
        ports:
            - "7551:5000"
        depends_on:
            - db
        environment:
            MONGODB_HOSTNAME: db
    db:
        image: mongo:latest
